const students = [{
        id: 1,
        fullName: "Ella Clark",
        email: "pvan0@washington.edu",
        gender: " Sex: Female",
        stateOfOrigin: "Delta State",
        job: "Tutor",
        Courses: "Coding",
    },
    {
        id: 2,
        fullName: "Victor Barny",
        email: "mgain1@ustream.tv",
        gender: " Sex: Male",
        stateOfOrigin: "Delta State",
        job: "Student",
        Courses: "Coding",

    },
    {
        id: 3,
        fullName: "David Samspson",
        email: "mgarmon2@myspace.com",
        gender: " Sex: Male",
        stateOfOrigin: "New York",
        job: "Tutor",
        Courses: "Coding",
    },
    {
        id: 4,
        fullName: "Luelle Aluard",
        email: "laluard3@reverbnation.com",
        gender: " Sex: Female",
        job: "student",
        stateOfOrigin: "New York",
    },
    {
        id: 5,
        fullName: "Sawyere Jesteco",
        email: "sjesteco4@wp.com",
        gender: " Sex: Male",
        job: "Tutor",
        stateOfOrigin: "New York",
    },
    {
        id: 6,
        fullName: "Jacquelynn Jacques",
        email: "jjacques5@yahoo.co.jp",
        gender: " Sex: Male",
        stateOfOrigin: "New York",
        job: "student",
        Courses: "Cyber Security",
    },
    {
        id: 7,
        fullName: "Skye Brinicombe",
        email: "sbrinicombe6@oakley.com",
        gender: " Sex: Female",
        stateOfOrigin: "New York",
        job: "Tutor",
        Courses: "Cyber Security",
    },
    {
        id: 8,
        fullName: "Thatcher Milan",
        email: "tmilan7@netlog.com",
        gender: " Sex: Male",
        job: "student",
        stateOfOrigin: "New York",
    },
    {
        id: 9,
        fullName: "Tallou Vigus",
        email: "tvigus8@sbwire.com",
        gender: " Sex: Male",
        job: "Tutor",
        stateOfOrigin: "New York",
    },
    {
        id: 10,
        fullName: "Alyssa Fido",
        email: "afido9@umn.edu",
        gender: " Sex: Male",
        job: "student",
        stateOfOrigin: "New York",
    },
    {
        id: 11,
        fullName: "Jecho Pergens",
        email: "jpergensa@state.gov",
        gender: " Sex: Male",
        job: "Tutor",
        stateOfOrigin: "New York",
    },
    {
        id: 12,
        fullName: "Tessie Healeas",
        email: "thealeasb@freewebs.com",
        gender: " Sex: Male",
        stateOfOrigin: "Provincie Gelderland",
        job: "Student",
        Courses: "Cyber Security",

    },
    {
        id: 13,
        fullName: "Leroy McUre",
        email: "lmcurec@etsy.com",
        gender: " Sex: Male",
        stateOfOrigin: "New York",
        job: "tutor",
    },
    {
        id: 14,
        fullName: "Tremain Coatts",
        email: "tcoattsd@dell.com",
        gender: " Sex: Female",
        stateOfOrigin: "Akwa-ibom State",
        job: "Student",
    },
    {
        id: 15,
        fullName: "Xerxes Kyllford",
        email: "xkyllforde@mail.ru",
        gender: " Sex: Female",
        stateOfOrigin: "Rivers State",
        job: "tutor",
    },
    {
        id: 16,
        fullName: "Corney Szimoni",
        email: "cszimonif@paginegialle.it",
        gender: " Sex: Female",
        stateOfOrigin: "Delta State",
        job: "Tutor",
    },
    {
        id: 17,
        fullName: "Elinor Ethridge",
        email: "eethridgeg@washingtonpost.com",
        gender: " Sex: Female",
        job: "student",
        stateOfOrigin: "Abia State",
    },
    {
        id: 18,
        fullName: "Addy Thomazet",
        email: "athomazeth@posterous.com",
        gender: " Sex: Female",
        stateOfOrigin: "Rivers State",
        job: "Tutor",

    },
    {
        id: 19,
        fullName: "Lolita Serck",
        email: "lsercki@networksolutions.com",
        gender: " Sex: Female",
        stateOfOrigin: "Imo State",
        job: "Tutor",
    },
    {
        id: 20,
        fullName: "Burk Trayhorn",
        email: "btrayhornj@symantec.com",
        gender: " Sex: Female",
        stateOfOrigin: "Cross Rivers State",
        job: "Tutor",
    },
    {
        id: 21,
        fullName: "Essa Tom",
        email: "btrayhornj@symantec.com",
        gender: "Male",
        stateOfOrigin: "Cross Rivers State",
        job: "Tutor",
    },
];

export default students;